[package]
name = "rust"
version = "0.1.0"
edition = "2021"

[dependencies]
futures-util = "0.3.31"
rust_socketio = { version = "*", features = ["async"] }
serde_json = "1.0.134"
tokio = { version = "*", features = ["full"] }
